employee Cli created
infoshareacademy/ehj1-uNasDziala pull request #15
Opened 2022-04-07 20:54 UTC by pmajewski7

Cześć,

przygotowałem CLI dla employee w oparciu o metody z pull request Marty.

2022-04-07 21:07 UTC, MateuszTarasewicz commented on src/main/java/com/isa/unasdziala/cli/MainCli.java
> +                case 2 -> EmployeeCli.run();
zmień case na 1

2022-04-08 17:49 UTC, MateuszTarasewicz requested changes

2022-04-08 17:49 UTC, MateuszTarasewicz commented on src/main/java/com/isa/unasdziala/cli/EmployeeCli.java
> +            switch (userOption) {
Tu wywołujemy metody CLI - które po pobraniu inputów od użytkownika dopiero wywołają metody service i ewentualnie wyświetlą dla użytkownika dane na konsoli loggerem

2022-04-09 20:54 UTC, pmajewski7 commented on src/main/java/com/isa/unasdziala/cli/EmployeeCli.java
> +            switch (userOption) {
Dodałem nowe metody. Zobacz proszę czy jeszcze trzeba coś zmienić.

2022-04-10 18:23 UTC, closed without merging